name: Deploy Google Cloud Function

on:
  push:
    branches: [ master ]
    paths-ignore: 
      - '**/README.md'
      - '**/*.yml'
  pull_request:
    branches: [ master ]
  workflow_dispatch:

env:
  PORT: 3000

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - id: auth
      uses: google-github-actions/auth@v0.4.0
      with:
        credentials_json: ${{ secrets.GCP_CREDENTIALS }}
    - id: deploy
      uses: google-github-actions/deploy-cloud-functions@v0.6.0
      with:
        name: drillresults
        runtime: nodejs14